Add root permission check to show_attached_IPs script

diff --git a/basics_1/1-show_attached_IPs b/basics_1/1-show_attached_IPs
--- a/basics_1/1-show_attached_IPs
+++ b/basics_1/1-show_attached_IPs
@@ -1,3 +1,7 @@
 #!/usr/bin/env bash
 #show attached IPs
+if [ "$EUID" -ne 0 ]; then
+  echo "Error: Please run this script as root or using sudo."
+  exit 1
+fi
  cat /etc/hosts
